### ISSUE TITLE
R markdown is `rmd` in vscode

### ISSUE THREAD

**Issue by albert-ying** [idleberg/vscode-emoji-code#34]
Hi, regarding to the #33 , the R markdown is named as `rmd` in vscode. I've fixed it locally, it would be nice if you could fix it before next release!

**Comment by idleberg** [comment]
Thanks for the notice. It turns out that different packages treat this differently.

- [bsouthga/vscode-rmarkdown](bsouthga/vscode-rmarkdown) uses `rmarkdown`
- [TianyiShi2001/rmarkdown-vscode](https://github.com/TianyiShi2001/rmarkdown-vscode/blob/2c5903bc93330991bc389c3344e4018902b1625f/package.json#L32) uses `rmarkdown`
- [REditorSupport/vscode-R](https://github.com/REditorSupport/vscode-R/blob/cd8d30d11d06eea33df8239f8ed2fd0c5cf1ee57/package.json#L161) uses `rmd`

So, I guess we'll have to support both 😉

**Comment by idleberg** [comment]
fixed in v0.11.2
